website/models.py
from flask_login import UserMixin
from sqlalchemy.sql import func
from . import db


class Article(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(150))
    description = db.Column(db.String(6500))
    date = db.Column(db.DateTime(timezone=True), default=func.now())

class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(20), unique=True)
    password = db.Column(db.String(20))

website/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager

db = SQLAlchemy()
DB_NAME = 'database.db'

def create_app():
    app = Flask(__name__)
    app.config['SECRET_KEY'] = "ashdhashdha shdashdhashfhasdh"
    app.config['SQLALCHEMY_DATABASE_URI'] = f'sqlite:///{DB_NAME}'
    db.init_app(app)

    from .views import views
    from .auth import auth
    from .models import User, Article

    app.register_blueprint(views, url_prefix='/')
    app.register_blueprint(auth, url_prefix='/')

    with app.app_context():
        db.create_all()
    
    
    login_manager = LoginManager()
    login_manager.login_view = 'auth.Login'
    login_manager.init_app(app)

    @login_manager.user_loader
    def load_user(id):
        return User.query.get(int(id))
    
    
    return app

website/auth.py
from flask import Blueprint, request, render_template, flash, redirect, url_for
from .models import User
from flask_login import login_user, login_required, logout_user


auth = Blueprint('auth', __name__)

admin = User(username = 'Admin',password= 'Admin')
guest = User(username = 'Guest',password= 'Guest')


@auth.route('/login', methods=['GET', 'POST'])
def Login():
    if request.method == 'POST':
        if request.form:
            username = request.form.get('name')
            password = request.form.get('password')
            user = User.query.filter_by(username=username).first()
            if user:
                if user.password == password:
                    flash(f'Welcome {user.username} !', category='success')
                    login_user(user, remember=True)
                    return redirect(url_for('views.Admin'))
                else:
                    flash('Passwords dont match', category='error')
            else:
                flash(f'There is no user about with {user}', category='error')
    return render_template('login.html')

@auth.route('/logout')
@login_required
def Logout():
    logout_user()
    return redirect(url_for('auth.Login'))

website/views.py
from flask import Blueprint, render_template, redirect, url_for, request, flash
from flask_login import login_required, current_user
from .auth import admin
from .models import Article
from . import db
from sqlalchemy import update


views = Blueprint('views', __name__)

@views.route('/')
def Intro():
    return render_template('introduction.html',user=current_user)


@views.route('/admin')
@login_required
def Admin():
    if current_user.username == admin.username and current_user.password == admin.password:
        list_article = db.session.query(Article).all()
        return render_template('admin_section.html', user=current_user,list_article=list_article )
    else:
        return redirect(url_for('views.Intro'))
    

@views.route('/new', methods=["GET", "POST"])
@login_required
def NewArticle():
    if request.method == 'POST':
        if request.form:
            title = request.form.get('title')
            description = request.form.get('description')
            new_article = Article(title=title, description=description)
            db.session.add(new_article)
            db.session.commit()
            flash('Article added' , category='success')
            return redirect(url_for('views.Admin'))
        else:
            flash('Please enter the informations' ,category="error")
    else:
        pass
    return render_template('new_article.html', user=current_user)

@views.route('/delete/<int:id>')
@login_required
def Delete(id):
    d = db.session.get(Article, id)
    db.session.delete(d)
    db.session.commit()
    return redirect(url_for("views.Admin"))

@views.route('/edit/<int:id>', methods=['GET', 'POST'])
@login_required
def Update(id):
    if request.method == 'POST':
        if request.form:
            title = request.form.get('title2')
            description = request.form.get('description2')
            article = db.session.query(Article).filter(Article.id == id)
            update = dict(title=title, description=description)
            article.update(update)
            article.session.commit()
            return redirect(url_for('views.Admin'))       
    return render_template('update_article.html', user=current_user)

@views.route('/article/<int:id>')
@login_required
def ArticleDetail(id):
    d = db.session.get(Article, id)
    return render_template('detail_article.html', user=current_user, d=d)

@views.route('/home')
@login_required
def Home():
    list_article = db.session.query(Article).all()
    return render_template('home.html', user=current_user, list_article=list_article)

website/templates/admin_section.html
{% extends 'base.html' %}
{% block body_content %}
<div class="container bg-light mt-5 p-4" style="width: 600px; height: 700px;">
    <div class="row">
            <h2 class="ml-4">Personal Blog</h2>
            <div class="ml-auto">
                <a href="{{url_for('views.NewArticle')}}" class="btn btn-success ml-2">+ Add</a>
            </div>
        <ul class="articlelist col-12 p-3 ml-3">
            {% for d in list_article%}
                <li>
                    <div class="d-flex">
                        <a href="/article/{{d.id}}" class="mt-2"><strong>{{d.title}}</strong></a> 
                        <div class="ml-auto">
                            <a href="/edit/{{d.id}}" class="btn btn-light">Edit</a>
                            <a href="/delete/{{d.id}}" class="btn btn-danger">Delete</a>
                        </div>
                    </div>
                    <br>
                </li>
            {% endfor %}
        </ul>
    </div>
</div>
{% endblock %}

website/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/static/style.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body class="bg-dark text-monospace">
    <nav class="navbar navbar-expand-lg bg-dark" style="font-size: 25px;">
        <a class="navbar-brand text-warning" href="{{url_for('views.Intro')}}" style="font-size: 30px;"><strong><i>Personal Blog</i></strong></a>
        <div class="collapse navbar-collapse">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item mr-2">
              <a class="nav-link" href="{{url_for('views.Intro')}}">Introduction</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{{url_for('views.Home')}}">Guest-Section</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{url_for('views.Admin')}}">Admin-Section</a>
            </li>
          </ul>
          {% if user %}
            <div class="navbar-right">
              <a class="nav-link" href="{{url_for('auth.Logout')}}">{{user.username}} - Logout</a>
            </div>
          {% else %}
            <div class="navbar-right">
              <a class="nav-link" href="{{url_for('auth.Login')}}">Login</a>
            </div>
          {% endif %}
        </div>
    </nav>
      {% with messages = get_flashed_messages(with_categories=true)%}
        {% if messages %}
            {% for category, message in messages %}
              {% if category == "error"%}
                  <div class="alert alert-danger alter-dismissable fade show" role="alert" id="div_flash">
                    {{ message }}
                    <button type="button" onclick="removeFlash()" class="float-right"> <span aria-hidden="true">&times;</span></button>
                  </div>
              {% else %}
                  <div class="alert alert-success alter-dismissable fade show" role="alert" id="div_flash">
                    {{ message }}
                    <button type="button" onclick="removeFlash()" class="float-right"> <span aria-hidden="true">&times;</span></button>
                  </div>
              {% endif %}
            {% endfor %}
        {% endif %}
      {% endwith%}
    {% block body_content %}
    {% endblock %}
    <script src="../static/main.js"></script>
</body>
</html>

website/templates/detail_article.html
{% extends 'base.html' %}
{% block body_content %}
<div class="container bg-light mt-5 p-4" style="width: 600px; height: 700px;">
    <div class="row">
        <h2 class="ml-4">{{d.title}}</h2>
        <div class="ml-auto">
            {% if current_user.username == 'Admin'%}
                <a href="{{url_for('views.Admin')}}" class="btn btn-light ml-2">
                    <span style='font-size:20px;'>&#8617;</span>
                </a>
            {% else %}
                <a href="{{url_for('views.Home')}}" class="btn btn-light ml-2">
                    <span style='font-size:20px;'>&#8617;</span>
                </a>
            {% endif %}
        </div>
        <ul class="articlelist col-12 p-3 ml-3">
            <li>
                <p>{{d.date}}</p>
            </li>
            <li>
                <p>{{d.description}}</p>
            </li>
        </ul>
    </div>
</div>
{% endblock %}

website/templates/home.html
{% extends 'base.html' %}
{% block body_content %}
<div class="container bg-light mt-5 p-4" style="width: 600px; height: 700px;">
    <div class="row">
        <h2 class="ml-4">Personal Blog</h2>
        <ul class="articlelist col-12 p-3 ml-3">
            {% for d in list_article%}
                <li>
                    <div class="d-flex">
                        <a href="/article/{{d.id}}" class="mt-2"><strong>{{d.title}}</strong></a> 
                        <div class="ml-auto">
                            <p>{{d.date}}</p>
                        </div>
                    </div>
                    <br>
                </li>
            {% endfor %}
        </ul>
    </div>
</div>
{% endblock %}

website/templates/introduction.html
{% extends 'base.html' %}

{% block body_content %}
    <div class="container d-flex justify-content-center mt-5 text-light">
        <div class="d-inline">
            <div class="row">
                <div class="col-12">
                    <h2 style="text-align: center;">Welcome to the Personal Blog!</h2>
                    <br>
                </div>
                <div class="col-6">
                    <h4>The Project Idea From Roadmap.sh</h4>
                    <br>
                    <h4>Thanks to roadmap.sh for project idea</h4>
                    <br>
                    <span style="font-size: 100px; margin-left: 200px;">&hearts;</span>
                </div>
                <div class="col-6">
                    <h4>For Guest Section, login with:</h4>
                    <h4>username:Guest, password:Guest</h4>
                    <br>
                    <h4>For Admin Section, login with:</h4>
                    <h4>username:Admin, password:Admin</h4>
                    <br>
                    <h4>You should login for see other pages.</h4>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

website/templates/login.html
{% extends 'base.html' %}

{% block body_content %}
    <div class="container mt-5 d-flex justify-content-center p-5 bg-light" style="width: 400px; height: 400px;">
        <div class="d-inline">
            <h1 class="ml-4">Login</h1>
            <form action="" method="post" class="mt-4">
                <label for="">Username:</label>
                <br>
                <input type="text" placeholder="name" name="name">
                <br>
                <br>
                <label for="">Password:</label>
                <br>
                <input type="password" name="password">
                <br>
                <br>
                <input class="btn btn-success" type="submit" value="Enter">
                <input class="btn btn-danger" type="reset" value="Clear">
            </form>
        </div>
    </div>
{% endblock %}

website/templates/new_article.html
{% extends 'base.html' %}
{% block body_content %}
<div class="container mt-5 d-flex justify-content-center p-5 bg-light" style="width: 500px; height: 550px;">
    <div class="d-inline">
        <h1>New Article</h1>
        <form action="" method="post" class="mt-3">
            <input type="text" placeholder="Article Title" name="title" style="width: 348px; height: 40px;" required>
            <br>
            <textarea name="description" id="" cols="37" rows="10" required>Content</textarea>
            <br>
            <input class="btn btn-success mt-2" type="submit" value="Publish">
        </form>
    </div>
</div>
{% endblock %}

website/templates/update_article.html
{% extends 'base.html' %}
{% block body_content %}
<div class="container mt-5 d-flex justify-content-center p-5 bg-light" style="width: 500px; height: 550px;">
    <div class="d-inline">
        <h2>Update Article</h2>
        <form action="" method="post" class="mt-3">
            <input type="text" placeholder="Article Title" name="title2" style="width: 348px; height: 40px;" required>
            <br>
            <textarea name="description2" id="" cols="37" rows="10" required>Content</textarea>
            <br>
            <input class="btn btn-success mt-2" type="submit" value="Update">
        </form>
    </div>
</div>
{% endblock %}